# Generated by Django 4.2.7 on 2025-12-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("size", models.DecimalField(decimal_places=8, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "raw_ticks",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timestamp"],
                        name="raw_ticks_symbol_83c768_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessedBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1s", "1 Second"),
                            ("1m", "1 Minute"),
                            ("5m", "5 Minutes"),
                        ],
                        max_length=3,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("open", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close", models.DecimalField(decimal_places=8, max_digits=20)),
                ("volume", models.DecimalField(decimal_places=8, max_digits=20)),
                ("tick_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "processed_bars",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timeframe", "timestamp"],
                        name="processed_b_symbol_44cd14_idx",
                    )
                ],
                "unique_together": {("symbol", "timeframe", "timestamp")},
            },
        ),
    ]
