# Generated by Django 4.2.7 on 2025-12-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("zscore_high", "Z-Score High"),
                            ("zscore_low", "Z-Score Low"),
                            ("correlation_break", "Correlation Break"),
                            ("volume_spike", "Volume Spike"),
                            ("price_movement", "Price Movement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("symbol_pair", models.CharField(db_index=True, max_length=50)),
                ("condition", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("triggered", "Triggered"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trigger_value",
                    models.DecimalField(decimal_places=8, max_digits=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpreadAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol_pair", models.CharField(db_index=True, max_length=50)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("timeframe", models.CharField(max_length=3)),
                ("symbol1_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("symbol2_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("hedge_ratio", models.DecimalField(decimal_places=6, max_digits=10)),
                ("spread", models.DecimalField(decimal_places=8, max_digits=20)),
                ("z_score", models.DecimalField(decimal_places=4, max_digits=10)),
                ("rolling_mean", models.DecimalField(decimal_places=8, max_digits=20)),
                ("rolling_std", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "correlation",
                    models.DecimalField(decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "adf_statistic",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "adf_pvalue",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                ("is_cointegrated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "spread_analytics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol_pair", "timeframe", "timestamp"],
                        name="spread_anal_symbol__e24d72_idx",
                    )
                ],
                "unique_together": {("symbol_pair", "timeframe", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="PriceStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("timeframe", models.CharField(max_length=3)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("returns", models.DecimalField(decimal_places=6, max_digits=10)),
                ("volatility", models.DecimalField(decimal_places=6, max_digits=10)),
                ("volume_ma", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "price_change_pct",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "high_low_range",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "price_stats",
                "ordering": ["-timestamp"],
                "unique_together": {("symbol", "timeframe", "timestamp")},
            },
        ),
    ]
